### ISSUE TITLE
У Кулинара не загружается логотип

### ISSUE THREAD

**Issue by Dum4G** [TaurerMedia/TaurerPlus#1]
https://tv.taurer.org/iptv_content/logos/KULINAR_TEMP.png

Сначала была ошибка, что подгрузка картинок из сторонних источников (hot loading) запрещена хостингом, теперь 404
![image](https://github.com/TaurerMedia/TaurerPlus/assets/5430116/c812ca73-1ec8-4c81-94e3-2744ba8e8bc1)

**Comment by TaurerMedia** [comment]
Здравствуйте! 

Спасибо за ваш репорт.
Ссылка на логотип будет добавлена 19.06.2024.

Спасибо за помощь в поиске неисправностей!

**Comment by TaurerMedia** [comment]
Здравствуйте!

Логотип был добавлен.

Закрываем репорт.
