### ISSUE TITLE
Не работают каналы с сервера nl1

### ISSUE THREAD

**Issue by Dum4G** [TaurerMedia/TaurerPlus#2]
Все каналы с https://nl1.live-stream.plus.taurer.org:443 попросту не загружаются

**Comment by TaurerMedia** [comment]
Здравствуйте!

Спасибо за ваш репорт.
Потоки на основные каналы были успешно обновлены. Технические потоки имеют свойство не работать в определённое время если они не требуются для вещания.

Спасибо за помощь в поиске неисправностей!
